VKhardwares/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from VKhardwares.form import LoginForm



urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html', authentication_form = LoginForm ), name = 'login'),
    path('register/', views.RegistrationView.as_view(), name = 'register'),
    path('about/', views.aboutus, name = 'about'),
    path('contact/',views.contact,name = 'contact'),
    path('',include('hardware.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page = 'index'), name = 'logout'),



]

hardware/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'hardware'

urlpatterns = [  
    path('', views.index, name = 'index'),
    path('set-session-data/', views.set_session_data, name='set_session_data'),
    path('product/<slug:slug>/', views.detail, name ='product'),
    path('category/',views.all_categories, name ='categories'),
    path('category/<slug:slug>/',views.category_products, name ='categories_product'),

    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('update-cart/<int:cart_id>/', views.update_cart, name="update-cart"),
    path('cart/', views.cart, name='cart'),
    path('order/',views.order,name= 'order'),
    path('success/', views.success, name='success'),


    path('user_profile/', views.profile, name="profile"),
    path('add-address/', views.AddressView.as_view(), name="add-address"),
    path('remove-address/<int:id>/', views.remove_address, name="remove-address"),

    path('search/',views.search, name='search'),
    
  
   



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add_address.html
{% extends 'base.html' %}
{% load static %}
    
    {% block content %}
<!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>Add Address</h2>
              <p>Home <span>-</span>Address</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->

<section class="contact-section padding_top">
    <div class="container">
                     <div class="d-none d-sm-block mb-5 pb-4">
                      

      </div> 


      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Address</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form" method="post" id="contactForm" action="{% url 'hardware:add-address' %}" novalidate="novalidate">
           <fieldset>
            {% csrf_token %}

            {% for fm in form %}
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                    {{fm.label_tag}}
                            {{fm}}

                  
            </div>
            {% endfor %}
            <!-- <div class="form-group mt-3"> -->
              <button class="btn_3 button-contactForm" type="submit">Submit</button>
            <!-- </div> -->
        </fieldset> 

         {% if form.non_field_errors %}
                {% for error in non_field_errors %}
                    <p class="alert alert-danger my-3">
                        {{error}}
                    </p>
                {% endfor %}
              {% endif %}
          </form>
        </div>
        
      </div>
    </div>
  </section>
  {% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="zxx">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>VK Hardware</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %} ">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'header.html' %}

    <div class="page-holder">
    

    {% block content %}

    {% endblock content %}

    {% include 'footer.html' %}


    {% include 'script.html' %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-8">
              <div class="breadcrumb_iner">
                <div class="breadcrumb_iner_item">
                  <h2>contact us</h2>
                  <p>Home <span>-</span> contact us</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- breadcrumb start-->
    
      <!-- ================ contact section start ================= -->
      <section class="contact-section padding_top">
        <div class="container">
          <div class="d-none d-sm-block mb-5 pb-4">
            <div id="map" style="height: 480px;"></div>
            <script>
              function initMap() {
                var uluru = {
                  lat: -25.363,
                  lng: 131.044
                };
                var grayStyles = [{
                    featureType: "all",
                    stylers: [{
                        saturation: -90
                      },
                      {
                        lightness: 50
                      }
                    ]
                  },
                  {
                    elementType: 'labels.text.fill',
                    stylers: [{
                      color: '#ccdee9'
                    }]
                  }
                ];
                var map = new google.maps.Map(document.getElementById('map'), {
                  center: {
                    lat: -31.197,
                    lng: 150.744
                  },
                  zoom: 9,
                  styles: grayStyles,
                  scrollwheel: false
                });
              }
            </script>
            <script
              src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap">
            </script>
    
          </div>
    
    
          <div class="row">
            <div class="col-12">
              <h2 class="contact-title">Get in Touch</h2>
            </div>
            <div class="col-lg-8">
              <form class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm"
                novalidate="novalidate">
                <div class="row">
                  <div class="col-12">
                    <div class="form-group">
    
                      <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9"
                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'"
                        placeholder='Enter Message'></textarea>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <input class="form-control" name="name" id="name" type="text" onfocus="this.placeholder = ''"
                        onblur="this.placeholder = 'Enter your name'" placeholder='Enter your name'>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''"
                        onblur="this.placeholder = 'Enter email address'" placeholder='Enter email address'>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''"
                        onblur="this.placeholder = 'Enter Subject'" placeholder='Enter Subject'>
                    </div>
                  </div>
                </div>
                <div class="form-group mt-3">
                  <a href="#" class="btn_3 button-contactForm">Send Message</a>
                </div>
              </form>
            </div>
            <div class="col-lg-4">
              <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-home"></i></span>
                <div class="media-body">
                  <h3>Vadakuzhiyil Hardwares</h3>
                  <p>Asramam jn, Poomthoppu</p>
                </div>
              </div>
              <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                <div class="media-body">
                  <h3>+91 8921162631</h3>
                  <p>Mon to sat 9am to 6pm</p>
                </div>
              </div>
              <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-email"></i></span>
                <div class="media-body">
                  <h3>vasebastian@gmail.com</h3>
                  <p>Send us your query anytime!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>



    {% endblock content %}

templates/footer.html
    <!--::footer_part start::-->
    <footer class="footer_part">
        <div class="container">
            <div class="row justify-content-around">
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Top Products</h4>
                        <ul class="list-unstyled">
                            <li><a href="">Managed Website</a></li>
                            <li><a href="">Manage Reputation</a></li>
                            <li><a href="">Power Tools</a></li>
                            <li><a href="">Marketing Service</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Quick Links</h4>
                        <ul class="list-unstyled">
                            <li><a href="">Jobs</a></li>
                            <li><a href="">Brand Assets</a></li>
                            <li><a href="">Investor Relations</a></li>
                            <li><a href="">Terms of Service</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Features</h4>
                        <ul class="list-unstyled">
                            <li><a href="">Jobs</a></li>
                            <li><a href="">Brand Assets</a></li>
                            <li><a href="">Investor Relations</a></li>
                            <li><a href="">Terms of Service</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Resources</h4>
                        <ul class="list-unstyled">
                            <li><a href="">Guides</a></li>
                            <li><a href="">Research</a></li>
                            <li><a href="">Experts</a></li>
                            <li><a href="">Agencies</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <div class="single_footer_part">
                        <h4>Newsletter</h4>
                        <p>Heaven fruitful doesn't over lesser in days. Appear creeping
                        </p>
                        <div id="mc_embed_signup">
                            <form target="_blank"
                                action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                method="get" class="subscribe_form relative mail_part">
                                <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                    class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = ' Email Address '">
                                <button type="submit" name="submit" id="newsletter-submit"
                                    class="email_icon newsletter-submit button-contactForm">subscribe</button>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="copyright_part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="copyright_text">
                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="footer_icon social_icon">
                            <ul class="list-unstyled">
                                <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#" class="single_social_icon"><i class="fas fa-globe"></i></a></li>
                                <li><a href="#" class="single_social_icon"><i class="fab fa-behance"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->

templates/header.html
{% load static %}
 
 <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="index.html"> <img src="{% static 'img/vk.png' %}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>
    
                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'hardware:index' %}">Home</a>
                                </li>

                        <!-- 
                                <li class="nav-item">
                                    <a class="nav-link" href="{#% url 'hardware:product' %#}">PRODUCT</a>
                                </li> 
                            -->

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Category
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        <a class="dropdown-item" href="{% url 'hardware:categories' %}"> shop category</a>
                                      <!--  <a class="dropdown-item" href="product.html">product details</a>-->
                                        
                                    </div>
                                </li>
                                
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'about' %}">About us</a>
                                </li>
                                {% if not request.user.is_authenticated %}

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="{% url 'login' %}" id="navbarDropdown_2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Login
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                        <a class="dropdown-item" href="{% url 'login' %}">Login</a>  
                                        <a class="dropdown-item" href="{% url 'register' %}">Signup</a>   
                                    </div>
                                </li>
                                {% endif %}


                                {% if request.user.is_authenticated %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="index.html" id="navbarDropdown_2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      My Account
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                    <a class="dropdown-item" href="{% url 'hardware:profile' %}">My Profile</a>
                                    <a class="dropdown-item" href="{% url 'hardware:order' %}">My Orders</a> 
                                    <a class="dropdown-item" href="{% url 'hardware:cart' %}">shopping cart</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                                    
                                  
                                    
                                    </div>
                                </li>
                                {% endif %}

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                                </li>

                        
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex">
                            <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <a href=""><i class="ti-heart"></i></a>
                         <div class="dropdown cart"> 
                                <a class="dropdown-toggle" href="" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-cart-plus"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <div class="single_product">
    
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        
        <div class="search_input" id="search_input_box" style="display: none;">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input"  name='q' placeholder="Search Here">
                    <button type="submit"  formaction="{% url 'hardware:search' %}" class="btn"> <a href= "{% url 'hardware:search' %}"></a></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
 </header>

templates/login.html
<html><head>
    <title>LOGIN</title>

    
    <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
rel="stylesheet"
/>

</head>
    <body>
        <section class="vh-100" style="background-color: #c6dfff;">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                  <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
          
                      <h3 class="mb-5">Login</h3>
                      <form  method="post">
                        {% csrf_token %}


                        {% for fm in form %}
                        <div class="form-group">
                            {{fm.label_tag}}
                            {{fm}}
                            <small class="text-danger">{{fm.errors|striptags}}</small>
                        </div>
                    {% endfor %}
          
                
          
                      <!-- Checkbox -->
                      <div class="form-check d-flex justify-content-start mb-4">
                        <input class="form-check-input" type="checkbox" value="" id="form1Example3" />
                        <label class="form-check-label" for="form1Example3"> Remember password </label>
                      </div>

                      {% if form.non_field_errors %}
                      {% for error in form.non_field_errors %}
                          <p class="alert alert-danger alert-dismissible fade show" role="alert" my-3">
                              {{error}}
                          </p>
                      {% endfor %}
                    {% endif %}
          
                      <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
          
                      <hr class="my-4">
          
                      <button class="btn btn-lg btn-block btn-primary" style="background-color: #dd4b39;"
                        type="submit"><i class="fab fa-google me-2"></i> Sign in with google</button>
                      <button class="btn btn-lg btn-block btn-primary mb-2" style="background-color: #3b5998;"
                        type="submit"><i class="fab fa-facebook-f me-2"></i>Sign in with facebook</button>
                      </form>
          
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
    </body>
    <!-- MDB -->
<script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
></script>

</html>

templates/order.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
      <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>User Profile</h2>
              <p>Home <span>-</span> Orders</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->
  <section class="confirmation_part padding_top">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
              <div class="order_details_iner">
                <h3>Order Details</h3>
                <table class="table table-borderless">
                  <thead>
                    <tr>
                      <th scope="col" colspan="2">#</th>
                      <th scope="col">Title</th>
                      <th scope="col">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% if orders %}
                    {% for order in orders %}
                    <tr>
                      <th colspan="2"><span>{{order.product.title}}{{forloop.counter}}</span></th>
                      <th>{{order.product.title}}</th>
                      <th> <span>{{order.status}}</span></th>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td class="text-danger" colspan="3">You've not Ordered anything yet.</td>
                      </tr>
                      {% endif %}
                   
                  </tbody>
                 
                
                </table>
              </div>
            </div>
          </div>

    </div>
    </section>


  {% endblock content %}

templates/user_profile.html
 {% extends 'base.html' %}
{% load static %}

    {% block content %}
      <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>User Profile</h2>
              <p>Home <span>-</span> User Profile</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->
    <section class="confirmation_part padding_top">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
             <!-- <div class="confirmation_tittle">
                <span>Thank you. Your order has been received.</span>
              </div>-->
            </div>
            <div class="col-lg-6 col-lx-4">
              <div class="single_confirmation_details">
                <h4>User Details</h4>
                <ul>
                  <li>
                    <p>Username</p><span>: {{request.user.username}}</span>
                  </li>
                  <li>
                    <p>Email</p><span>: {{request.user.email}}</span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-lg-6 col-lx-4">
              <div class="single_confirmation_details">
                <h4>Billing Address {{forloop.counter}} <i> <a href="{% url 'hardware:add-address' %}"class='fa fa-plus-square'></a></i></h4>
                <hr>
                {% if addresses %}
                    {% for address in addresses %}


                <h4> Address {{forloop.counter}} <i> <a href="{% url 'hardware:remove-address' address.id %}"class='fa fa-trash'></a></i></h4>
                <ul>
                  <li>
                    <p>Street</p><span>: {{address.locality}}</span>
                  </li>
                  <li>
                    <p>city</p><span>:{{address.city}} </span>
                  </li>
                  <li>
                    <p>State</p><span>: {{address.state}}</span>
                  </li>
                  
                  <hr>
                  {% endfor %}
                  {% else %}
                  <div class="text-danger">
                    Address not Added.
                  </div>
                  {% endif %}
                </ul>
              </div>
            </div>
            </div>


        
               
                    
        </div>
      </section>


    {% endblock content %}